'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ChevronDown, ChevronRight, Microscope, Zap, Beaker, Factory, FlaskConical, FileCheck } from 'lucide-react';
import CommentableContent from '../components/CommentableContent';


export default function ForMiners() {
  const [openSections, setOpenSections] = useState(new Set());
  const [openModalities, setOpenModalities] = useState(new Set());

  function toggleSection(key) {
    setOpenSections(prev => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  }
  function toggleModality(key) {
    setOpenModalities(prev => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  }

  return (
    <CommentableContent pageName="for-miners">
      <div className="min-h-screen py-8 px-12 space-y-6">

        {/* Box 1: Header */}
        <div className="flex gap-6 items-stretch">
          <div className="flex-1 bg-[#edede6] rounded-3xl p-10 shadow-xl border border-white">
            <h1 className="text-4xl font-bold text-[#264563] mb-3 leading-tight">Biology 101 for Mining Professionals</h1>
            <p className="text-xl text-[#264563]">
              If mining is going to use biology, you need to understand how biological systems interact with metals and minerals
            </p>
          </div>
          <div className="flex-1 rounded-3xl border-2 border-white shadow-xl" />
        </div>

        {/* Box 2: Definition + Sections */}
        <div className="bg-[#edede6] rounded-3xl shadow-2xl p-8 md:p-12 border border-white">

          {/* Key Insight */}
          <div className="mb-8">
            <h2 className="text-xl font-bold text-[#264563] mb-3">
              Biology as Switchable, Selective Chemistry
            </h2>
            <div className="text-[#264563] space-y-3">
              <p>
                Biology provides <strong>switchable, selective chemistry</strong> for metal extraction and management.
                Like reagents and catalysts, biological systems are constrained by temperature, pH, ionic strength, inhibitors, and
                substrate availability. Understanding these constraints is key to successful integration.
              </p>
              <div className="bg-[#264563]/5 rounded-lg p-4 border-l-4 border-[#264563] mt-4">
                <p className="text-[#264563]">
                  Think of biology not as a replacement for your flowsheet, but as a <strong>new class of reagent</strong>—one
                  that can adapt, self-regenerate, and operate selectively where conventional chemistry struggles.
                </p>
              </div>
              <p className="mt-4 font-semibold">
              This guide helps you understand how biological systems interact with metals and minerals and how they fit into mining processes.
              </p>
            </div>
          </div>
          {/* Biological Systems in Mining */}
          {/* Biological Systems in Mining */}
          <Section
            title="Biological Systems in Mining"
            icon={Zap}

            expanded={openSections.has('bioSystems')}
            onToggle={() => toggleSection('bioSystems')}
          >
            <BiologicalSystemsSection />
          </Section>
          
          {/* Mechanisms */}
          <Section
            title="Mechanisms of Metal Mobilization & Capture"
            icon={Beaker}
            expanded={openSections.has('mechanisms')}
            onToggle={() => toggleSection('mechanisms')}
          >
            <div className="space-y-4">
              <p className="text-[#264563] mb-4">
                Biological systems mobilize and capture metals through several mechanistic pathways. All can be engineered or tuned:
              </p>

              <MechanismCard
                title="Acidolysis"
                description="Production of acids (organic or inorganic) that break down, dissolve, or alter minerals"
                application="Important for carbonates and some sulfide minerals"
                example="Microbes oxidize sulfur to sulfuric acid (H₂SO₄), which attacks chalcopyrite (CuFeS₂)"
                color="amber"
                usedBy="Microbes"
              />

              <MechanismCard
                title="Redoxolysis"
                description="Oxidation or reduction of metals or ligands that controls solubility"
                application="ferrous iron (Fe²⁺) → ferric iron (Fe³⁺) oxidation, hexavalent uranium (U(VI)) → tetravalent uranium (U(IV)) reduction"
                example="Ferric iron (Fe³⁺) generated by microbes acts as an oxidant to leach copper from sulfides"
                color="blue"
                usedBy="Microbes"
              />

              <MechanismCard
                title="Complexolysis"
                description="Production of ligands that complex (bind) metals and keep them in solution"
                application="Metallophores, siderophores, organic acids"
                example="Microbes secrete organic acids that chelate rare earth elements"
                color="emerald"
                usedBy="Microbes, Biomolecules"
              />

              <MechanismCard
                title="Biosorption & Bioaccumulation"
                description="Metals stick to cell surfaces or EPS (biosorption), or are actively taken up and stored (bioaccumulation)"
                application="Rapid metal capture, often independent of metabolism"
                example="Algae and bacteria sorb heavy metals from acid mine drainage (AMD) on cell surfaces"
                color="teal"
                usedBy="Microbes, Phytomining"
              />

              <MechanismCard
                title="Bioprecipitation & Biomineralization"
                description="Microbial activity alters local chemistry, causing dissolved metals to precipitate from solution"
                application="Metal removal from solution in remediation and recovery systems"
                example="Sulfate-reducing bacteria (SRB) produce sulfide that precipitates copper (Cu), zinc (Zn), and other metals from solution"
                color="sky"
                usedBy="Microbes"
              />
            </div>
          </Section>

          {/* Biomining Modalities */}
          <Section
            title="Biomining Modalities & Flowsheets"
            icon={Factory}
            expanded={openSections.has('modalities')}
            onToggle={() => toggleSection('modalities')}
          >
            <div className="space-y-6">

              {/* Classical Bioleaching & Biooxidation */}
              <div className="bg-[#264563]/5 rounded-xl p-5 border border-[#264563]/20">
                <h3 className="text-lg font-bold text-[#264563] mb-4 pb-2 border-b border-[#264563]/20">
                  Classical Bioleaching & Biooxidation
                </h3>
                <div className="space-y-4">
                  <ModalityCard
                    title="Dump & Heap Bioleaching"
                    description="Low-grade sulfide ores piled on pads and irrigated with acidic ferric solutions. Native or inoculated acidophiles catalyze Fe & S oxidation and metal release."
                    applications="Common for copper sulfide ores, with growing interest for other sulfides"
                    parameters={[
                      "Time: Months to years",
                      "Temperature: Ambient to ~50°C",
                      "pH: 1.5-2.5",
                      "Scale: Very large (Mt)"
                    ]}
                    integration={
                      <> Comminution → <strong>Bioleaching</strong> → PLS → SX/EW → metal cathodes </>
                    }
                    challenges="Passivation layers, channeling, oxygen/nutrient limitations"
                    expanded={openModalities.has('dump')}
                    onToggle={() => toggleModality('dump')}
                  />

                  <ModalityCard
                    title="Stirred-Tank Biooxidation"
                    description="Refractory gold or polymetallic sulfide concentrates oxidized in aerated reactors prior to cyanidation or other leaching."
                    applications="Proven technology for refractory gold (BIOX®, BacTech)"
                    parameters={[
                      "Time: Days to weeks",
                      "Temperature: 40-50°C (mesophile) or 65-85°C (thermophile)",
                      "pH: 1.5-2.0",
                      "Scale: Moderate (kt concentrate)"
                    ]}
                    integration={
                       <>Flotation → <strong>biooxidation</strong> → cyanidation → recovery</>
                    }
                    challenges="Capital intensive, energy costs, solids loading limits"
                    expanded={openModalities.has('stirred')}
                    onToggle={() => toggleModality('stirred')}
                  />

                  <ModalityCard
                    title="In-Situ & In-Stope Bioleaching"
                    description="Injection of lixiviants and/or microbes into permeable deposits underground or in fractured zones."
                    applications="Attractive for low-grade or inaccessible deposits"
                    parameters={[
                      "Time: Years",
                      "Temperature: Variable (geothermal gradient)",
                      "pH: Controlled by injection",
                      "Scale: Highly variable"
                    ]}
                    integration={
                      <>Injection wells → <strong>bioleaching</strong> → collection → processing</>
                    }
                    challenges="Geotechnical risks, regulatory hurdles, containment"
                    expanded={openModalities.has('insitu')}
                    onToggle={() => toggleModality('insitu')}
                  />
                </div>
              </div>

              {/* Advanced Bioseparations & Waste Recovery */}
              <div className="bg-[#264563]/5 rounded-xl p-5 border border-[#264563]/20">
                <h3 className="text-lg font-semibold text-[#264563] mb-4 pb-2 border-b border-[#264563]/20">
                  Advanced Bioseparations & Waste Recovery
                </h3>

                <EmerginTechCard
                  expanded={openModalities.has('emerging')}
                  onToggle={() => toggleModality('emerging')}
                />

                <BioremediationCard
                  expanded={openModalities.has('bioremediation')}
                  onToggle={() => toggleModality('bioremediation')}
                />
              </div>
            </div>
          </Section>

          {/* Evaluation Checklist */}
          <Section
            title="Evaluation Checklist for Bio-Solutions"
            icon={FileCheck}
            expanded={openSections.has('checklist')}
            onToggle={() => toggleSection('checklist')}
          >
            <div className="bg-white rounded-lg p-6 border border-[#264563]/20">
              <p className="text-[#264563] font-medium mb-4">
                Before dismissing or adopting a bio-solution, ask these questions:
              </p>
              <div className="space-y-4">
                {[
                  {
                    q: "What problem is it actually solving?",
                    detail: "New resource access, cost reduction, impurity management, water quality, closure risk, social license?"
                  },
                  {
                    q: "What is the technology-readiness level (TRL) and evidence base?",
                    detail: "Lab vs. pilot vs. commercial references. Performance in representative feedstocks, not just synthetic solutions."
                  },
                  {
                    q: "Time scales and integration",
                    detail: "Does it fit within existing residence times? Can it run as a side-stream or bleed-stream process?"
                  },
                  {
                    q: "Risk and monitoring",
                    detail: "What monitoring (sensors, assays) is required? What happens if it fails or stops?"
                  },
                  {
                    q: "Regulatory and public-perception impacts",
                    detail: "Does it simplify permitting (less chemical transport, lower emissions)? Does it improve closure outcomes and community relations?"
                  }
                ].map((item, i) => (
                  <div key={i}>
                    <div className="flex items-start gap-3">
                      <div className="bg-[#264563] text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 text-sm font-bold" style={{marginTop: '0.1em'}}>
                        {i + 1}
                      </div>
                      <div>
                        <p className="text-[#264563] font-semibold">{item.q}</p>
                        <p className="text-[#264563] text-sm mt-1">{item.detail}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Section>

          {/* Navigation */}
          <div className="mt-12 flex justify-between">
            <Link href="/" className="text-[#264563] hover:text-[#1e3450] flex items-center gap-2">
              ← Back to Home
            </Link>
            <Link href="/complex-materials" className="text-[#264563] hover:text-[#1e3450] flex items-center gap-2">
              Explore Complex Materials →
            </Link>
          </div>
        </div>

      </div>
    </CommentableContent>
  );
}
function BiologicalSystemsSection() {
  const [openSubsections, setOpenSubsections] = useState(new Set());

  function toggleSubsection(key) {
    setOpenSubsections(prev => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  }

  return (
    <div className="space-y-6">
      <p className="text-[#264563]">
        Biology enters mining in three main forms: 
      </p>

      <div className="rounded-xl border border-[#264563]/20 overflow-hidden bg-white">
        <button
          onClick={() => toggleSubsection('living')}
          className="w-full p-5 flex items-center justify-between hover:bg-[#264563]/5 transition-colors"
        >
          <h3 className="text-lg font-semibold text-[#264563]">
            Microbial Systems
          </h3>
          {openSubsections.has('living') ? (
            <ChevronDown className="w-5 h-5 text-[#264563]" />
          ) : (
            <ChevronRight className="w-5 h-5 text-[#264563]" />
          )}
        </button>

        {openSubsections.has('living') && (
          <div className="p-6 pt-0 border-t border-[#264563]/10 space-y-6">
            <div className="pt-4 space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">What Microbes Are</h4>
              <p>
                Microorganisms (microbes) are microscopic living organisms such as bacteria, archaea, and fungi. Unlike chemical reagents or materials, they are living systems that grow, reproduce, and actively respond to their environment.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Microbes Work</h4>
              <p>
                Microorganisms operate by carrying out chemical reactions to obtain energy from their environment. These reactions allow them to power their metabolism, maintain cellular processes, and produce new cells.
              </p>
              <p>
                At a high level, microbes need three things to survive and do work:
              </p>
              <div className="grid md:grid-cols-3 gap-4">
                <NeedCard
                  title="Energy Source"
                  examples={[
                    "Light (not relevant here)",
                    "Oxidation of ferrous iron (Fe²⁺)",
                    "Reduced sulfur compounds",
                    "Organic carbon"
                  ]}
                />
                <NeedCard
                  title="Electron Donors/Acceptors"
                  examples={[
                    "ferrous iron (Fe²⁺) / ferric iron (Fe³⁺)",
                    "Reduced/oxidized sulfur",
                    "molecular oxygen (O₂), nitrate, sulfate",
                  ]}
                />
                <NeedCard
                  title="Carbon Source"
                  examples={[
                    "carbon dioxide (CO₂) (autotrophs)",
                    "Organic carbon (heterotrophs)",
                    "Mixed modes"
                  ]}
                />
              
              </div>
              <p className="italic">
              In practice, some substances serve multiple functions depending on the organism and metabolism.
              </p>
              </div>  
            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Microbes Interact With Minerals</h4>
              <p>
              Microbes influence how metals move because their metabolism changes the chemistry of minerals and surrounding fluids. These changes can dissolve minerals, expose valuable metals for recovery, or form new minerals that capture or stabilize metals.
              Think of familiar processes such as baking bread or turning milk into cheese — microbes drive reactions that gradually alter materials and their environment to produce valuable products.
              </p>
            </div>
          </div>
        )}
      </div>

      <div className="rounded-xl border border-[#264563]/20 overflow-hidden bg-white">
        <button
          onClick={() => toggleSubsection('nonliving')}
          className="w-full p-5 flex items-center justify-between hover:bg-[#264563]/5 transition-colors"
        >
          <h3 className="text-lg font-semibold text-[#264563]">
            Biomolecular Systems
          </h3>
          {openSubsections.has('nonliving') ? (
            <ChevronDown className="w-5 h-5 text-[#264563]" />
          ) : (
            <ChevronRight className="w-5 h-5 text-[#264563]" />
          )}
        </button>

        {openSubsections.has('nonliving') && (
          <div className="p-6 pt-0 border-t border-[#264563]/10 space-y-6">
            <div className="pt-4 space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">What Biomolecules Are</h4>
              <p>
                Biomolecular systems use biological molecules such as proteins, peptides, polysaccharides, or other bio-derived materials to interact with metals. Unlike microbes, these are not living systems — they do not grow, reproduce, or metabolize.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Biomolecules Work</h4>
              <p>
                Biomolecules interact with metals through specific chemical binding sites on their molecular structure, which can coordinate (trap) metal ions and hold them in place. In natural biological systems, these interactions allow organisms to transport, store, and control metals needed for cellular processes. 
              </p>
              
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Biomolecules Are Used in Mining</h4>
              <p>
                Biomolecular systems leverage these natural metal-binding interactions to selectively capture, concentrate, or separate metals from complex solutions. These interactions can pull target metals out of mixed streams, remove unwanted impurities, or recover metals from dilute solutions.
              </p>
              <p>
                At a high level, biomolecular systems function in three steps:
              </p>
                <div className="grid md:grid-cols-3 gap-4">
                  <NeedCard
                    title="Selective Binding"
                    examples={[
                      "Biomolecules bind specific metals",
                      "Binding can be highly selective",
                      "Enables capture of metals from complex mixtures"
                    ]}
                  />
                  <NeedCard
                    title="Seperation"
                    examples={[
                      "Bound metals stay on the biomolecule",
                      "Target metal concentrates"
                    ]}
                  />
                  <NeedCard
                    title="Release & Recovery"
                    examples={[
                      "Conditions are adjusted to release the bound metal",
                      "Metal is recovered in a concentrated stream",
                      "Biomolecules can often be reused"
                    ]}
                  />
                  </div>
                  <p className="italic">
                  In practice, performance depends not just on binding strength, but also on selectivity, stability, and the ability to regenerate the material.
                  </p>
              
            </div>
          </div>
        )}
      </div>

      <div className="rounded-xl border border-[#264563]/20 overflow-hidden bg-white">
        <button
          onClick={() => toggleSubsection('phyto')}
          className="w-full p-5 flex items-center justify-between hover:bg-[#264563]/5 transition-colors"
        >
          <h3 className="text-lg font-semibold text-[#264563]">
            Phytomining
          </h3>
          {openSubsections.has('phyto') ? (
            <ChevronDown className="w-5 h-5 text-[#264563]" />
          ) : (
            <ChevronRight className="w-5 h-5 text-[#264563]" />
          )}
        </button>

        {openSubsections.has('phyto') && (
          <div className="p-6 pt-0 border-t border-[#264563]/10 space-y-6">
            <div className="pt-4 space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">What Phytomining Is</h4>
              <p>
                Phytomining uses plants to extract metals from soils, mine waste, or low-grade deposits. Certain plants, known as hyperaccumulators, naturally absorb and concentrate metals in their tissues.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Phytomining Works</h4>
              <p>
                Plants take up dissolved metals from the soil through their roots as part of normal nutrient uptake. These metals are transported through the plant and stored in leaves, stems, or other tissues.
              </p>
              <p>
                At a high level, phytomining systems perform in three steps:
              </p>

              <div className="grid md:grid-cols-3 gap-4">
                <NeedCard
                  title="Uptake"
                  examples={[
                    "Plant roots absorb dissolved metals from soil or water",
                    "Metals enter the plant through normal nutrient transport pathways"
                  ]}
                />
                <NeedCard
                  title="Transport & Accumulation"
                  examples={[
                    "Metals move through the plants vascular system",
                    "Some species concentrate metals in leaves, stems, or other tissues"
                  ]}
                />
                <NeedCard
                  title="Stable & Reusable Material"
                  examples={[
                    "Metal-rich biomass is harvested",
                    "Metals are recovered from the plant material through processing"
                  ]}
                />
              </div>

              <p className="italic">
                The most widely used application is the bioremediation of metal-contaminated soils.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Plants Interact With Metals</h4>
              <p>
                Plants influence how metals move through soils by absorbing dissolved metal ions through their roots and transporting them through their tissues. In some species, metals can accumulate to very high concentrations in leaves, stems, or other plant parts, allowing metals to be concentrated in biomass.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
    );
    }
function Section({ title, icon: Icon, expanded, onToggle, children }) {
  return (
    <div className="rounded-xl mb-4 border-2 border-white overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full bg-[#264563] p-6 flex items-center justify-between hover:bg-[#1e3450] transition-colors"
      >
        <div className="flex items-center gap-3">
          <Icon className="w-6 h-6 text-white" />
          <h2 className="text-xl font-bold text-white">{title}</h2>
        </div>
        {expanded ? <ChevronDown className="w-6 h-6 text-white" /> : <ChevronRight className="w-6 h-6 text-white" />}
      </button>
      {expanded && <div className="bg-[#edede6] p-6 border-t border-white/20">{children}</div>}
    </div>
  );
}

function NeedCard({ title, examples }) {
  return (
    <div className="bg-white rounded-lg p-4 border border-[#264563]/20">
      <h3 className="text-lg font-bold text-[#264563] mb-2">{title}</h3>
      <ul className="space-y-1">
        {examples.map((ex, i) => (
          <li key={i} className="text-[#264563] text-sm flex items-start gap-2">
            <span className="text-[#264563]" style={{marginTop: '0.05em'}}>→</span>
            <span>{ex}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function MicrobeCard({ name, examples, function: func, relevance }) {
  return (
    <div className="bg-white rounded-lg p-4 border border-[#264563]/20">
      <h4 className="text-lg font-bold text-[#264563]">{name}</h4>
      <p className="text-[#264563]/50 text-xs mt-1 italic">{examples}</p>
      <p className="text-[#264563] text-sm mt-2"><strong>Function:</strong> {func}</p>
      <p className="text-[#264563] text-sm mt-1"><strong>Relevance:</strong> {relevance}</p>
    </div>
  );
}

function MechanismCard({ title, description, application, example, color, usedBy }) {
  const colorClasses = {
    blue:    { border: 'border-[#264563]',   text: 'text-[#264563]' },
    amber:   { border: 'border-amber-500',   text: 'text-amber-500' },
    emerald: { border: 'border-emerald-700', text: 'text-emerald-700' },
    teal:    { border: 'border-teal-500',    text: 'text-teal-500' },
    sky:     { border: 'border-sky-500',     text: 'text-sky-500' },
  };
  const { border, text } = colorClasses[color] || colorClasses.blue;

  return (
    <div className={`rounded-lg p-4 border bg-white ${border}`}>
      <div className="flex items-start justify-between mb-1">
        <h3 className={`text-lg font-bold ${text}`}>{title}</h3>
        <span className="text-xs font-medium text-[#264563]/60 bg-[#264563]/5 rounded px-2 py-0.5 ml-3 whitespace-nowrap">Biological system(s): {usedBy}</span>
      </div>
      <p className="text-[#264563] text-sm mb-2">{description}</p>
      <p className="text-[#264563] text-sm mb-2">
        <strong>Application:</strong> {application}
      </p>
      <div className="bg-white rounded p-2 border border-[#264563]/10">
        <p className="text-[#264563] text-xs">
          <strong>Example:</strong> {example}
        </p>
      </div>
    </div>
  );
}

function EmerginTechCard({ expanded, onToggle }) {
  return (
    <div className="rounded-xl border-2 border-white overflow-hidden mt-4">
      <button
        onClick={onToggle}
        className="w-full bg-[#264563] px-6 py-4 flex items-center justify-between hover:bg-[#1e3450] transition-colors"
      >
        <h4 className="text-base font-bold text-white">Emerging Technologies for REEs & Complex Matrices</h4>
        {expanded ? <ChevronDown className="w-5 h-5 text-white flex-shrink-0" /> : <ChevronRight className="w-5 h-5 text-white flex-shrink-0" />}
      </button>
      {expanded && (
        <div className="bg-white p-5">
          <p className="text-[#264563] text-sm mb-7">Biomolecular ligands and non-chromatographic formats that selectively capture and concentrate rare earth elements and critical metals from complex, dilute feed streams.</p>
          <div className="grid grid-cols-3 gap-3 mb-7">
            <div className="bg-[#264563]/5 rounded-lg p-3 border border-[#264563]/20">
              <p className="text-[#264563] font-semibold text-xs mb-1">Protein/Peptide-Based Ligands</p>
              <p className="text-[#264563]/70 text-xs">(e.g., lanmodulin) for selective REE capture</p>
            </div>
            <div className="bg-[#264563]/5 rounded-lg p-3 border border-[#264563]/20">
              <p className="text-[#264563] font-semibold text-xs mb-1">Hybrid Biomolecular Ligands</p>
              <p className="text-[#264563]/70 text-xs">Peptides + polymers for improved manufacturability</p>
            </div>
            <div className="bg-[#264563]/5 rounded-lg p-3 border border-[#264563]/20">
              <p className="text-[#264563] font-semibold text-xs mb-1">Non-Chromatographic Deployments</p>
              <p className="text-[#264563]/70 text-xs">Membranes, beads, structured packings for PLS polishing</p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 mb-3">
            <div>
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Applications</p>
              <p className="text-[#264563] text-sm mb-7">Coal by-products, phosphogypsum, red mud, spent catalysts, magnet scrap</p>
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Integration</p>
              <p className="text-[#264563] text-sm">
                Feed stream → <strong>selective binding</strong> → elution & recovery → purified metal stream
              </p>
            </div>
            <div className="pl-16">
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Key Parameters</p>
              <ul className="text-[#264563] text-sm space-y-1">
                <li>• Time: Minutes to hours</li>
                <li>• Temperature: Ambient (~20–40°C)</li>
                <li>• pH: Typically 3–6 (feed dependent)</li>
                <li>• Scale: Modular (columns, membranes, contactors)</li>
              </ul>
            </div>
          </div>
          <div className="bg-orange-50 rounded p-2 border border-orange-500 w-1/2">
            <p className="text-xs font-semibold text-orange-500 mb-1">Common Challenges</p>
            <p className="text-orange-600 text-sm">Matrix effects, fouling, immobilization strategies, feed chemistry variability</p>
          </div>
        </div>
      )}
    </div>
  );
}

function BioremediationCard({ expanded, onToggle }) {
  return (
    <div className="rounded-xl border-2 border-white overflow-hidden mt-4">
      <button
        onClick={onToggle}
        className="w-full bg-[#264563] px-6 py-4 flex items-center justify-between hover:bg-[#1e3450] transition-colors"
      >
        <h4 className="text-base font-bold text-white">Bioremediation & Recovery from Waste</h4>
        {expanded ? <ChevronDown className="w-5 h-5 text-white flex-shrink-0" /> : <ChevronRight className="w-5 h-5 text-white flex-shrink-0" />}
      </button>
      {expanded && (
        <div className="bg-white p-5">
          <p className="text-[#264563] text-sm mb-7">Biological systems that remove or recover metals from mine drainage, waste streams, and secondary sources — converting liabilities into recoverable resources.</p>
          <div className="grid grid-cols-3 gap-3 mb-7">
            <div className="bg-[#264563]/5 rounded-lg p-3 border border-[#264563]/20">
              <p className="text-[#264563] font-semibold text-xs mb-1">AMD/ARD Bioremediation</p>
              <p className="text-[#264563]/70 text-xs">Constructed wetlands, SRB bioreactors, and algae systems that remove metals and raise pH</p>
            </div>
            <div className="bg-[#264563]/5 rounded-lg p-3 border border-[#264563]/20">
              <p className="text-[#264563] font-semibold text-xs mb-1">Metal Recovery from AMD</p>
              <p className="text-[#264563]/70 text-xs">Selective sorbents and biomineralization to recover copper (Cu), zinc (Zn), REEs, and other metals</p>
            </div>
            <div className="bg-[#264563]/5 rounded-lg p-3 border border-[#264563]/20">
              <p className="text-[#264563] font-semibold text-xs mb-1">E-waste & Urban Mining</p>
              <p className="text-[#264563]/70 text-xs">Bioleaching and biosorption applied to circuit boards, magnets, and electronics</p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 mb-3">
            <div>
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Applications</p>
              <p className="text-[#264563] text-sm mb-7">Mine drainage treatment, tailings reprocessing, legacy site remediation, e-waste and magnet scrap</p>
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Integration</p>
              <p className="text-[#264563] text-sm">Parameters and integration pathways vary by technique and site conditions</p>
            </div>
            <div className="pl-16">
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Key Parameters</p>
              <p className="text-[#264563] text-sm">• Highly site- and technique-dependent</p>
            </div>
          </div>
          <div className="bg-orange-50 rounded p-2 border border-orange-500 w-1/2">
            <p className="text-xs font-semibold text-orange-500 mb-1">Common Challenges</p>
            <p className="text-orange-600 text-sm">Long treatment timescales, regulatory and discharge compliance</p>
          </div>
        </div>
      )}
    </div>
  );
}

function ModalityCard({ title, description, applications, parameters, integration, challenges, expanded, onToggle }) {
  return (
    <div className="rounded-xl border-2 border-white overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full bg-[#264563] px-6 py-4 flex items-center justify-between hover:bg-[#1e3450] transition-colors"
      >
        <h4 className="text-base font-bold text-white">{title}</h4>
        {expanded ? <ChevronDown className="w-5 h-5 text-white flex-shrink-0" /> : <ChevronRight className="w-5 h-5 text-white flex-shrink-0" />}
      </button>
      {expanded && (
        <div className="bg-white p-5 border-t border-white/20">
          <p className="text-[#264563] text-sm mb-7">{description}</p>

          <div className="grid grid-cols-2 gap-4 mb-3">
            <div>
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Applications</p>
              <p className="text-[#264563] text-sm mb-7">{applications}</p>
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Integration</p>
              <p className="text-[#264563] text-sm">{integration}</p>
            </div>
            <div className="pl-16">
              <p className="text-sm font-semibold text-[#264563] mb-1 underline">Key Parameters</p>
              <ul className="text-[#264563] text-sm space-y-1">
                {parameters.map((p, i) => <li key={i}>• {p}</li>)}
              </ul>
            </div>
          </div>

          <div className="bg-orange-50 rounded p-2 border border-orange-500 w-1/2">
            <p className="text-xs font-semibold text-orange-500 mb-1">Common Challenges</p>
            <p className="text-orange-600 text-sm">{challenges}</p>
          </div>
        </div>
      )}
    </div>
  );
}
