'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ChevronDown, ChevronRight, Microscope, Zap, Beaker, Factory, FlaskConical, FileCheck } from 'lucide-react';
import CommentableContent from '../components/CommentableContent';


export default function ForMiners() {
  const [expandedSection, setExpandedSection] = useState(null);

  return (
    <CommentableContent pageName="for-miners">
      <div className="min-h-screen py-8 px-12 space-y-6">

        {/* Box 1: Header */}
        <div className="flex gap-6 items-stretch">
          <div className="flex-1 bg-[#edede6] rounded-3xl p-10 shadow-xl border border-white">
            <h1 className="text-4xl font-bold text-[#264563] mb-3 leading-tight">Biology 101 for Mining Professionals</h1>
            <p className="text-xl text-[#264563]">
              If mining is going to use biology, you need to understand how microbes and biomolecules interact with metals and minerals.
            </p>
          </div>
          <div className="flex-1 rounded-3xl border-2 border-white shadow-xl" />
        </div>

        {/* Box 2: Definition + Sections */}
        <div className="bg-[#edede6] rounded-3xl shadow-2xl p-8 md:p-12 border border-white">

          {/* Key Insight */}
          <div className="mb-8">
            <h2 className="text-xl font-bold text-[#264563] mb-3">
              Biology as Switchable, Selective Chemistry
            </h2>
            <div className="text-[#264563] space-y-3">
              <p>
                Biology provides <strong>switchable, selective chemistry</strong> for metal extraction and management.
                Like reagents and catalysts, microbes and biomolecules are constrained by temperature, pH, ionic strength, inhibitors, and
                substrate availability. Understanding these constraints is key to successful integration.
              </p>
              <div className="bg-[#264563]/5 rounded-lg p-4 border-l-4 border-[#264563] mt-4">
                <p className="text-[#264563]">
                  Think of biology not as a replacement for your flowsheet, but as a <strong>new class of reagent</strong>—one
                  that can adapt, self-regenerate, and operate selectively where conventional chemistry struggles.
                </p>
              </div>
              <p className="mt-4 font-semibold">
              This guide helps you understand how biological systems interact with metals and minerals and how they fit into mining processes.
              </p>
            </div>
          </div>
          {/* Biological Systems in Mining */}
          {/* Biological Systems in Mining */}
          <Section
            title="Biological Systems in Mining"
            icon={Zap}
            expanded={expandedSection === 'bioSystems'}
            onToggle={() => setExpandedSection(expandedSection === 'bioSystems' ? null : 'bioSystems')}
          >
            <BiologicalSystemsSection />
          </Section>
          
          {/* Mechanisms */}
          <Section
            title="Mechanisms of Metal Mobilization & Capture"
            icon={Beaker}
            expanded={expandedSection === 'mechanisms'}
            onToggle={() => setExpandedSection(expandedSection === 'mechanisms' ? null : 'mechanisms')}
          >
            <div className="space-y-4">
              <p className="text-[#264563] mb-4">
                Microbes mobilize and capture metals through several mechanistic pathways. All can be engineered or tuned:
              </p>

              <MechanismCard
                title="Acidolysis"
                description="Production of acid (e.g., H₂SO₄) that dissolves minerals"
                application="Critical for sulfides and carbonates"
                example="Microbes oxidize sulfur to sulfuric acid, which attacks chalcopyrite (CuFeS₂)"
                color="amber"
              />

              <MechanismCard
                title="Redoxolysis"
                description="Oxidation or reduction of metals or ligands, controlling solubility"
                application="Fe²⁺ → Fe³⁺ oxidation, U(VI) → U(IV) reduction"
                example="Fe³⁺ generated by microbes acts as oxidant to leach copper from sulfides"
                color="blue"
              />

              <MechanismCard
                title="Complexolysis"
                description="Production of ligands that complex metals and keep them in solution"
                application="Metallophores, siderophores, organic acids"
                example="Microbes secrete organic acids that chelate rare earth elements"
                color="emerald"
              />

              <MechanismCard
                title="Biosorption & Bioaccumulation"
                description="Metals stick to cell surfaces/EPS or are actively taken up and stored"
                application="Rapid, often not directly tied to metabolism"
                example="Algae and bacteria accumulate heavy metals from AMD on cell surfaces"
                color="teal"
              />

              <MechanismCard
                title="Bioprecipitation / Biomineralization"
                description="Microbial activity alters local chemistry to precipitate new minerals"
                application="Changes pH, redox, carbonate, or sulfide levels"
                example="SRB produce sulfide that precipitates Cu, Zn, and other metals from solution"
                color="sky"
              />
            </div>
          </Section>

          {/* Biomining Modalities */}
          <Section
            title="Biomining Modalities & Flowsheets"
            icon={Factory}
            expanded={expandedSection === 'modalities'}
            onToggle={() => setExpandedSection(expandedSection === 'modalities' ? null : 'modalities')}
          >
            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-[#264563] mb-3">
                Classical Bioleaching & Biooxidation
              </h3>

              <ModalityCard
                title="Dump / Heap Bioleaching"
                description="Low-grade sulfide ores piled on pads and irrigated with acidic ferric solutions. Native or inoculated acidophiles catalyze Fe/S oxidation and metal release."
                applications="Common for copper, increasingly for other sulfides"
                parameters={[
                  "Time: Months to years",
                  "Temperature: Ambient to 50°C",
                  "pH: 1.5-2.5",
                  "Scale: Very large (Mt)"
                ]}
                integration="PLS → SX/EW → metal cathodes"
                challenges="Passivation layers, channeling, oxygen/nutrient limitations"
              />

              <ModalityCard
                title="Stirred-Tank Biooxidation"
                description="High-grade refractory gold or polymetallic concentrates oxidized in aerated reactors prior to cyanidation or other leach."
                applications="Proven technology for refractory gold (BIOX®, BacTech)"
                parameters={[
                  "Time: Days to weeks",
                  "Temperature: 40-50°C (mesophile) or 65-85°C (thermophile)",
                  "pH: 1.5-2.0",
                  "Scale: Moderate (kt concentrate)"
                ]}
                integration="Flotation → biooxidation → cyanidation → recovery"
                challenges="Capital intensive, energy costs, solids loading limits"
              />

              <ModalityCard
                title="In-Situ / In-Stope Bioleaching"
                description="Injection of lixiviants and/or microbes into permeable deposits underground or in fractured zones."
                applications="Attractive for low-grade or inaccessible deposits"
                parameters={[
                  "Time: Years",
                  "Temperature: Variable (geothermal gradient)",
                  "pH: Controlled by injection",
                  "Scale: Highly variable"
                ]}
                integration="Injection wells → collection → processing"
                challenges="Geotechnical risks, regulatory hurdles, containment"
              />

              <h3 className="text-lg font-semibold text-[#264563] mb-3 mt-8">
                Bioseparations & Advanced Flowsheets
              </h3>

              <div className="bg-[#264563]/5 rounded-lg p-5 border border-[#264563]/20">
                <h4 className="font-semibold text-[#264563] mb-3">Emerging Technologies for REEs & Complex Matrices</h4>
                <ul className="space-y-2 text-[#264563] text-sm">
                  <li className="flex items-start gap-2">
                    <span className="text-[#264563] mt-1">•</span>
                    <span><strong>Protein/peptide-based ligands</strong> (e.g., lanmodulin) for selective REE capture</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-[#264563] mt-1">•</span>
                    <span><strong>Hybrid biomolecular ligands</strong> – peptides + polymers for improved manufacturability</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-[#264563] mt-1">•</span>
                    <span><strong>Non-chromatographic deployments</strong> – membranes, beads, structured packings for PLS polishing</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-[#264563] mt-1">•</span>
                    <span><strong>Applications</strong>: Coal by-products, phosphogypsum, red mud, spent catalysts, magnet scrap</span>
                  </li>
                </ul>
                <p className="text-[#264563]/70 text-sm mt-3 italic">
                  Challenges: Matrix effects, fouling, immobilization strategies, feed chemistry variability
                </p>
              </div>

              <h3 className="text-lg font-semibold text-[#264563] mb-3 mt-8">
                Bioremediation & Recovery from Waste
              </h3>

              <div className="bg-[#264563]/5 rounded-lg p-5 border border-[#264563]/20">
                <ul className="space-y-3 text-[#264563] text-sm">
                  <li>
                    <strong className="text-[#264563]">AMD/ARD Bioremediation:</strong> Constructed wetlands,
                    SRB bioreactors, algae systems that remove metals and raise pH via sulfate reduction and metal sulfide precipitation
                  </li>
                  <li>
                    <strong className="text-[#264563]">Metal Recovery from AMD:</strong> Coupling bioremediation
                    with selective sorbents or biomineralization to recover Cu, Zn, REEs, and other metals
                  </li>
                  <li>
                    <strong className="text-[#264563]">E-waste & Urban Mining:</strong> Bioleaching and biosorption
                    applied to circuit boards, magnets, and electronics as alternative to high-temperature smelting
                  </li>
                </ul>
              </div>
            </div>
          </Section>

          {/* Evaluation Checklist */}
          <Section
            title="Evaluation Checklist for Bio-Solutions"
            icon={FileCheck}
            expanded={expandedSection === 'checklist'}
            onToggle={() => setExpandedSection(expandedSection === 'checklist' ? null : 'checklist')}
          >
            <div className="bg-white rounded-lg p-6 border border-[#264563]/20">
              <p className="text-[#264563] font-medium mb-4">
                Before dismissing or adopting a bio-solution, ask these questions:
              </p>
              <div className="space-y-4">
                {[
                  {
                    q: "What problem is it actually solving?",
                    detail: "New resource access, cost reduction, impurity management, water quality, closure risk, social license?"
                  },
                  {
                    q: "What is the technology-readiness level (TRL) and evidence base?",
                    detail: "Lab vs. pilot vs. commercial references. Performance in representative feedstocks, not just synthetic solutions."
                  },
                  {
                    q: "Time scales and integration",
                    detail: "Does it fit within existing residence times? Can it run as a side-stream or bleed-stream process?"
                  },
                  {
                    q: "Risk and monitoring",
                    detail: "What monitoring (sensors, assays) is required? What happens if it fails or stops?"
                  },
                  {
                    q: "Regulatory and public-perception impacts",
                    detail: "Does it simplify permitting (less chemical transport, lower emissions)? Does it improve closure outcomes and community relations?"
                  }
                ].map((item, i) => (
                  <div key={i} className="border-l-4 border-[#264563] pl-4">
                    <div className="flex items-start gap-3">
                      <div className="bg-[#264563] text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 mt-0.5 text-sm font-bold">
                        {i + 1}
                      </div>
                      <div>
                        <p className="text-[#264563] font-semibold">{item.q}</p>
                        <p className="text-[#264563] text-sm mt-1">{item.detail}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Section>

          {/* Navigation */}
          <div className="mt-12 flex justify-between">
            <Link href="/" className="text-[#264563] hover:text-[#1e3450] flex items-center gap-2">
              ← Back to Home
            </Link>
            <Link href="/complex-materials" className="text-[#264563] hover:text-[#1e3450] flex items-center gap-2">
              Explore Complex Materials →
            </Link>
          </div>
        </div>

      </div>
    </CommentableContent>
  );
}
function BiologicalSystemsSection() {
  const [expandedSubsection, setExpandedSubsection] = useState(null);

  return (
    <div className="space-y-6">
      <p className="text-[#264563]">
        Biology enters mining in two main forms: microbial systems that mobilize metals from solid materials and bio-derived systems that selectively capture metals from solution.
      </p>

      <div className="rounded-xl border border-[#264563]/20 overflow-hidden bg-white">
        <button
          onClick={() =>
            setExpandedSubsection(expandedSubsection === 'living' ? null : 'living')
          }
          className="w-full p-5 flex items-center justify-between hover:bg-[#264563]/5 transition-colors"
        >
          <h3 className="text-lg font-semibold text-[#264563]">
            Microbial Systems
          </h3>
          {expandedSubsection === 'living' ? (
            <ChevronDown className="w-5 h-5 text-[#264563]" />
          ) : (
            <ChevronRight className="w-5 h-5 text-[#264563]" />
          )}
        </button>

        {expandedSubsection === 'living' && (
          <div className="p-6 pt-0 border-t border-[#264563]/10 space-y-6">
            <div className="pt-4 space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">What Microbes Are</h4>
              <p>
                Microorganisms (microbes) are microscopic living organisms such as bacteria, archaea, and fungi. Unlike chemical reagents or materials, they are living systems that grow, reproduce, and actively respond to their environment.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Microbes Work</h4>
              <p>
                Microorganisms operate by carrying out chemical reactions to obtain energy from their environment. These reactions allow them to power their metabolism, maintain cellular processes, and produce new cells.
              </p>
              <p>
                At a high level, microbes need three things to survive and do work:
              </p>
              <div className="grid md:grid-cols-3 gap-4">
                <NeedCard
                  title="Energy Source"
                  examples={[
                    "Light (not relevant here)",
                    "Oxidation of Fe²⁺",
                    "Reduced sulfur compounds",
                    "Organic carbon"
                  ]}
                />
                <NeedCard
                  title="Electron Donors/Acceptors"
                  examples={[
                    "Fe²⁺ / Fe³⁺",
                    "Reduced/oxidized sulfur",
                    "O₂, nitrate, sulfate",
                  ]}
                />
                <NeedCard
                  title="Carbon Source"
                  examples={[
                    "CO₂ (autotrophs)",
                    "Organic carbon (heterotrophs)",
                    "Mixed modes"
                  ]}
                />
              
              </div>
              <p className="italic">
              In practice, some substances can serve multiple functions depending on the organism and metabolism.
              </p>
              </div>  
            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Microbes Interact With Minerals</h4>
              <p>
              Microbes influence how metals move because their metabolism changes the chemistry of minerals and surrounding fluids. These changes can dissolve minerals, expose valuable metals for recovery, or form new minerals that capture or stabilize metals.
              Think of familiar processes such as baking bread or turning milk into cheese — microbes drive reactions that gradually alter materials and their environment to produce valuable products.
              </p>
            </div>
          </div>
        )}
      </div>

      <div className="rounded-xl border border-[#264563]/20 overflow-hidden bg-white">
        <button
          onClick={() =>
            setExpandedSubsection(expandedSubsection === 'nonliving' ? null : 'nonliving')
          }
          className="w-full p-5 flex items-center justify-between hover:bg-[#264563]/5 transition-colors"
        >
          <h3 className="text-lg font-semibold text-[#264563]">
            Biomolecular Systems
          </h3>
          {expandedSubsection === 'nonliving' ? (
            <ChevronDown className="w-5 h-5 text-[#264563]" />
          ) : (
            <ChevronRight className="w-5 h-5 text-[#264563]" />
          )}
        </button>

        {expandedSubsection === 'nonliving' && (
          <div className="p-6 pt-0 border-t border-[#264563]/10 space-y-6">
            <div className="pt-4 space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">What Biomolecules Are</h4>
              <p>
                Biomolecular systems use biological molecules such as proteins, peptides, polysaccharides, or other bio-derived materials to interact with metals. Unlike microbes, these are not living systems — they do not grow, reproduce, or metabolize.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Biomolecules Work</h4>
              <p>
                Biomolecules interact with metals through specific chemical binding sites on their molecular structure. Functional groups such as carboxyl, amine, thiol, or phosphate groups can coordinate (trap) metal ions and hold them in place.
              </p>
              <p>
                At a high level, biomolecular systems need three things to perform:
              </p>

              <div className="grid md:grid-cols-3 gap-4">
                <NeedCard
                  title="Selective Binding"
                  examples={[
                    "Biomolecules recognize and bind specific metals through molecular binding sites",
                    "Highly selective interactions with target metals",
                    "Enables capture of metals from complex mixtures"
                  ]}
                />
                <NeedCard
                  title="Seperation"
                  examples={[
                    "Bound metals stay on the biomolecular material while the rest flows past",
                    "Target metal concentrates"
                  ]}
                />
                <NeedCard
                  title="Stable & Reusable Material"
                  examples={[
                    "Conditions are adjusted to release the bound metal",
                    "Metal returns to solution in a concentrated stream",
                    "Biomolecules can often be reused"
                  ]}
                />
              </div>

              <p className="italic">
                In practice, performance depends not just on binding strength, but also on selectivity, stability, and the ability to regenerate the material.
              </p>
            </div>

            <div className="space-y-3 text-[#264563]">
              <h4 className="text-base font-semibold">How Biomolecules Interact With Metals</h4>
              <p>
                Biomolecules influence how metals move by selectively binding, concentrating, or separating them from complex solutions. These interactions can pull target metals out of mixed streams, remove unwanted impurities, or help recover metals from dilute solutions. Think of this like a highly selective filter or molecular sorter — instead of changing the mineral itself, biomolecules recognize and capture specific metals once they are already in solution.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
    );
    }
function Section({ title, icon: Icon, expanded, onToggle, children }) {
  return (
    <div className="rounded-xl mb-4 border-2 border-white overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full bg-[#264563] p-6 flex items-center justify-between hover:bg-[#1e3450] transition-colors"
      >
        <div className="flex items-center gap-3">
          <Icon className="w-6 h-6 text-white" />
          <h2 className="text-xl font-bold text-white">{title}</h2>
        </div>
        {expanded ? <ChevronDown className="w-6 h-6 text-white" /> : <ChevronRight className="w-6 h-6 text-white" />}
      </button>
      {expanded && (
        <div className="bg-[#edede6] p-6 border-t border-white/20">
          {children}
        </div>
      )}
    </div>
  );
}

function NeedCard({ title, examples }) {
  return (
    <div className="bg-white rounded-lg p-4 border border-[#264563]/20">
      <h3 className="text-lg font-bold text-[#264563] mb-2">{title}</h3>
      <ul className="space-y-1">
        {examples.map((ex, i) => (
          <li key={i} className="text-[#264563] text-sm flex items-start gap-2">
            <span className="text-[#264563] mt-1">→</span>
            <span>{ex}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function MicrobeCard({ name, examples, function: func, relevance }) {
  return (
    <div className="bg-white rounded-lg p-4 border border-[#264563]/20">
      <h4 className="text-lg font-bold text-[#264563]">{name}</h4>
      <p className="text-[#264563]/50 text-xs mt-1 italic">{examples}</p>
      <p className="text-[#264563] text-sm mt-2"><strong>Function:</strong> {func}</p>
      <p className="text-[#264563] text-sm mt-1"><strong>Relevance:</strong> {relevance}</p>
    </div>
  );
}

function MechanismCard({ title, description, application, example, color }) {
  const colorClasses = {
    blue:    { border: 'border-[#264563]',   text: 'text-[#264563]' },
    amber:   { border: 'border-amber-500',   text: 'text-amber-500' },
    emerald: { border: 'border-emerald-700', text: 'text-emerald-700' },
    teal:    { border: 'border-teal-500',    text: 'text-teal-500' },
    sky:     { border: 'border-sky-500',     text: 'text-sky-500' },
  };
  const { border, text } = colorClasses[color] || colorClasses.blue;

  return (
    <div className={`rounded-lg p-4 border bg-white ${border}`}>
      <h3 className={`text-lg font-bold mb-1 ${text}`}>{title}</h3>
      <p className="text-[#264563] text-sm mb-2">{description}</p>
      <p className="text-[#264563] text-sm mb-2">
        <strong>Application:</strong> {application}
      </p>
      <div className="bg-white rounded p-2 border border-[#264563]/10">
        <p className="text-[#264563] text-xs">
          <strong>Example:</strong> {example}
        </p>
      </div>
    </div>
  );
}

function ModalityCard({ title, description, applications, parameters, integration, challenges }) {
  return (
    <div className="bg-white rounded-lg p-5 border border-[#264563]/20">
      <h4 className="text-lg font-bold text-[#264563] mb-2">{title}</h4>
      <p className="text-[#264563] text-sm mb-3">{description}</p>

      <div className="grid md:grid-cols-2 gap-4 mb-3">
        <div>
          <p className="text-xs font-semibold text-[#264563] mb-1">APPLICATIONS</p>
          <p className="text-[#264563] text-sm">{applications}</p>
        </div>
        <div>
          <p className="text-xs font-semibold text-[#264563] mb-1">KEY PARAMETERS</p>
          <ul className="text-[#264563] text-xs space-y-0.5">
            {parameters.map((p, i) => <li key={i}>• {p}</li>)}
          </ul>
        </div>
      </div>

      <div className="mb-2">
        <p className="text-xs font-semibold text-[#264563] mb-1">INTEGRATION</p>
        <p className="text-[#264563] text-sm">{integration}</p>
      </div>

      <div className="bg-orange-50 rounded p-2 border border-orange-500">
        <p className="text-xs font-semibold text-orange-500 mb-1">COMMON CHALLENGES</p>
        <p className="text-orange-600 text-xs">{challenges}</p>
      </div>
    </div>
  );
}
